FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /usr/local/app/

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -Ls https://github.com/block-core/blockcore-atomic-swaps/releases/download/#{VERSION}#/Blockcore.AtomicSwaps-#{VERSION}#-linux-x64.tar.gz \
    | tar -xvz -C .

EXPOSE 5500
ENTRYPOINT ["dotnet", "Blockcore.AtomicSwaps.Server.dll"]
